#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2015-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import http.server

...  # Python 3 is required

class RequestHandler(http.server.BaseHTTPRequestHandler):

    def do_GET(self):
        self.send_response(200)
        if 'relative' in self.path:
            fname = '../../../../../../tmp/moo'
        else:
            fname = '/tmp/moo'
        if '%' in self.path:
            cdv = 'attachment'
        else:
            cdv = 'attachment; filename="{fname}"'.format(fname=fname)
        self.send_header('Content-Disposition', cdv)
        self.end_headers()
        self.wfile.write(b'moo\n')

if __name__ == '__main__':
    http.server.test(RequestHandler)

# vim:ts=4 sts=4 sw=4 et
